<a href="https://colab.research.google.com/github/Fawad97/Feature_Extraction-BOW-TFIDF.ipynb/blob/main/Feature_Extraction_BOW%2CTFIDF%2CWord2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
texts = ["I love NLP", "NLP is great"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
print(X.toarray())

[[0 0 1 1]
 [1 1 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(texts)
print(X_tfidf.toarray())


[[0.         0.         0.81480247 0.57973867]
 [0.6316672  0.6316672  0.         0.44943642]]


In [ ]:
# Uninstall existing versions of gensim and numpy
!pip uninstall -y gensim numpy

# Install compatible versions. It's often helpful to explicitly install the desired numpy version
# before installing gensim, or let pip handle the dependency resolution by installing gensim first.
# Let's try installing gensim and let it pull in a compatible numpy version.
!pip install gensim

# Import the Word2Vec model
from gensim.models import Word2Vec

# The rest of your code
sentences = [["NLP", "is", "fun"], ["Word2Vec", "makes", "it", "easy"]]
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)
vector = model.wv['NLP']
print(vector)

Found existing installation: gensim 4.3.3
Uninstalling gensim-4.3.3:
  Successfully uninstalled gensim-4.3.3
Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
  Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
[ 8